In [1]:
import tensorflow as tf

In [2]:
ts_c = tf.constant(2, name='ts_c')

In [3]:
ts_c

<tf.Tensor 'ts_c:0' shape=() dtype=int32>

In [4]:
ts_x = tf.Variable(ts_c + 5, name='ts_x')

In [5]:
ts_x

<tf.Variable 'ts_x:0' shape=() dtype=int32_ref>

In [6]:
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('ts_c=', sess.run(ts_c))
    print('ts_x=', sess.run(ts_x))
    print('ts_c=', ts_c.eval(session=sess))
    print('ts_x=', ts_x.eval(session=sess))

ts_c= 2
ts_x= 7
ts_c= 2
ts_x= 7


In [7]:
width = tf.placeholder('int32', name='width')
height = tf.placeholder('int32', name='height')
area = tf.multiply(width, height, name='area')

In [8]:
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('area=', sess.run(area, feed_dict={width: 6, height: 8}))

area= 48


In [9]:
with tf.Session() as sess:
    tf.summary.merge_all()
    train_writer = tf.summary.FileWriter('log/area', sess.graph)

In [10]:
def tensor(ts_x):
    with tf.Session() as sess:
        init = tf.global_variables_initializer()
        sess.run(init)
        x = sess.run(ts_x)
        print(x, x.shape)

In [11]:
tensor(tf.Variable([0.4, 0.2, 0.4]))

[0.4 0.2 0.4] (3,)


In [12]:
tensor(tf.Variable([[0.4, 0.2, 0.4]]))

[[0.4 0.2 0.4]] (1, 3)


In [13]:
tensor(tf.Variable([[-0.5, -0.2], [-0.3, 0.4], [-0.5, 0.2]]))

[[-0.5 -0.2]
 [-0.3  0.4]
 [-0.5  0.2]] (3, 2)


In [14]:
x = tf.Variable([[1., 1., 1.]])
w = tf.Variable([[-0.5, -0.2], [-0.3, 0.4], [-0.5, 0.2]])
xw = tf.matmul(x, w)
tensor(xw)

[[-1.3  0.4]] (1, 2)


In [15]:
a = tf.Variable([[0.1, 0.2]])
b = tf.Variable([[-1.3, 0.4]])
sum = a + b
tensor(sum)

[[-1.1999999  0.6      ]] (1, 2)


In [16]:
xmw = tf.matmul(x, w) + a
tensor(xmw)

[[-1.1999999  0.6      ]] (1, 2)
